// Writes engine/tests/fixtures/games.txt: random games plus what the TypeScript
// rules and tactics say after every stone. The C++ engine must agree line for line.
// Usage: npx tsx scripts/gen-engine-fixtures.ts
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { hexDistance, type Hex } from '../src/shared/hex.ts';
import { Game, otherPlayer, type Player } from '../src/shared/rules.ts';
import { allCovers, threatWindows, winningMoves } from '../src/shared/tactics.ts';

const OUT = path.resolve(import.meta.dirname, '../../engine/tests/fixtures/games.txt');
const GAMES = 240;

/** Deterministic PRNG so the fixture file is reproducible. */
function mulberry32(seed: number) {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Order-independent 32-bit checksum of a cell set, identical in C++. */
function cellHash(h: Hex): number {
  return (Math.imul(h.q, 73856093) ^ Math.imul(h.r, 19349663)) >>> 0;
}

function describe(game: Game): string {
  const playable = game.playableCells();
  let sum = 0;
  for (const h of playable) sum = (sum + cellHash(h)) >>> 0;
  const mover: Player = game.current;
  const opp = otherPlayer(mover);
  const threatsX = threatWindows(game, 'X').length;
  const threatsO = threatWindows(game, 'O').length;
  const win1 = game.winner ? 0 : winningMoves(game, mover, 1).length;
  const win2 = game.winner ? 0 : winningMoves(game, mover, 2).length;
  // Smallest number of stones that touch every opponent threat (0, 1, 2), or 3 if two can't.
  const oppThreats = threatWindows(game, opp);
  let cover = 0;
  if (oppThreats.length > 0) {
    const one = allCovers(oppThreats, 1);
    cover = one.length > 0 ? 1 : allCovers(oppThreats, 2).length > 0 ? 2 : 3;
  }
  return [
    `playable=${playable.length}`,
    `sum=${sum}`,
    `winner=${game.winner ?? '-'}`,
    `current=${game.current}`,
    `turn=${game.turn}`,
    `left=${game.stonesLeft}`,
    `threatsX=${threatsX}`,
    `threatsO=${threatsO}`,
    `win1=${win1}`,
    `win2=${win2}`,
    `cover=${cover}`,
  ].join(' ');
}

const lines: string[] = [
  '# Generated by web/scripts/gen-engine-fixtures.ts from the TypeScript rules. Do not edit by hand.',
  '# game <id> <radius> then one "stone <q> <r> <facts>" line per stone, starting with the empty board.',
];

for (let id = 0; id < GAMES; id++) {
  const random = mulberry32(1000 + id);
  const radius = id % 3 === 2 ? 8 : 9;
  const game = new Game(radius);
  // Denser play in some games so lines, threats and wins actually happen.
  const reach = id % 4 === 0 ? 1 : id % 4 === 1 ? 2 : 3;
  const maxStones = 20 + Math.floor(random() * 140);
  lines.push(`game ${id} ${radius}`);
  lines.push(`empty ${describe(game)}`);
  // The first stone is sometimes off-center, since any cell within the radius is legal.
  while (!game.winner && game.moves.length < maxStones) {
    const pool =
      game.moves.length === 0
        ? game.playableCells()
        : game.playableCells().filter((h) => game.moves.some((s) => hexDistance(s, h) <= reach));
    const cells = pool.length > 0 && random() > 0.03 ? pool : game.playableCells();
    const pick = cells[Math.floor(random() * cells.length)]!;
    game.place(pick.q, pick.r);
    lines.push(`stone ${pick.q} ${pick.r} ${describe(game)}`);
  }
}

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, `${lines.join('\n')}\n`);
console.log(`wrote ${GAMES} games (${lines.length} lines) to ${OUT}`);
