"""Writes engine/tests/fixtures/planes.txt: positions from the shared game fixtures with the raw planes
planes.py builds for them, so the C++ engine can be checked against the trainer.

Format, one position per block:
  position <radius> <stone count> q r q r ...
  center <q> <r>
  plane <index> <hex>

<hex> packs the plane's 625 cells row by row into bytes, cell i in bit i % 8 of byte i // 8.
"""
from __future__ import annotations

import random
from pathlib import Path

import numpy as np

from planes import PLANES, raw_planes

ROOT = Path(__file__).resolve().parents[1]
GAMES = ROOT / "engine" / "tests" / "fixtures" / "games.txt"
OUT = ROOT / "engine" / "tests" / "fixtures" / "planes.txt"


def main() -> None:
    games, current = [], None
    for line in GAMES.read_text(encoding="utf-8").splitlines():
        words = line.split()
        if not words or words[0].startswith("#"):
            continue
        if words[0] == "game":
            current = (int(words[2]), [])
            games.append(current)
        elif words[0] == "stone" and current is not None:
            current[1].append((int(words[1]), int(words[2])))
    rng = random.Random(20260915)
    lines = [f"# generated by trainer/gen_plane_fixtures.py; planes: {' '.join(PLANES)}"]
    count = 0
    for radius, moves in games:
        for n in range(len(moves)):
            if n > 0 and rng.random() > 0.03:
                continue
            planes, center = raw_planes(moves[:n], radius)
            lines.append(f"position {radius} {n} " + " ".join(f"{q} {r}" for q, r in moves[:n]))
            lines.append(f"center {center[0]} {center[1]}")
            for p in range(len(PLANES)):
                bits = np.packbits(planes[p].ravel() > 0.5, bitorder="little")
                lines.append(f"plane {p} {bits.tobytes().hex()}")
            count += 1
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {count} positions to {OUT}")


if __name__ == "__main__":
    main()
